src/main/java/com/redhat/ecosystemappeng/config/CustomReflectionConfiguration.java
src/main/java/com/redhat/ecosystemappeng/config/ObjectMapperProducer.java
src/main/java/com/redhat/ecosystemappeng/model/ComponentRequest.java
src/main/java/com/redhat/ecosystemappeng/model/GraphRequest.java
src/main/java/com/redhat/ecosystemappeng/model/PackageRef.java
src/main/java/com/redhat/ecosystemappeng/model/graph/DependencyEdge.java
src/main/java/com/redhat/ecosystemappeng/routes/DependencyAnalytics.java
src/main/java/com/redhat/ecosystemappeng/routes/SnykIntegration.java
src/main/java/com/redhat/ecosystemappeng/routes/TideliftIntegration.java
src/main/java/com/redhat/ecosystemappeng/routes/TrustedContentIntegration.java
src/main/java/com/redhat/ecosystemappeng/routes/integration/Constants.java
src/main/java/com/redhat/ecosystemappeng/routes/integration/GraphUtils.java
src/main/java/com/redhat/ecosystemappeng/routes/integration/ProviderAggregationStrategy.java
src/main/java/com/redhat/ecosystemappeng/routes/integration/ReportTemplate.java
src/main/java/com/redhat/ecosystemappeng/routes/integration/VulnerabilityProvider.java
src/main/java/com/redhat/ecosystemappeng/snyk/SnykRequestBuilder.java
src/main/java/com/redhat/ecosystemappeng/tidelift/TideliftRequestBuilder.java
src/main/java/com/redhat/ecosystemappeng/trustedcontent/TrustedContentBodyMapper.java
src/test/java/com/redhat/ecosystemappeng/extensions/InjectWireMock.java
src/test/java/com/redhat/ecosystemappeng/extensions/WiremockV3Extension.java
src/test/java/com/redhat/ecosystemappeng/routes/DependencyAnalyticsIT.java
src/test/java/com/redhat/ecosystemappeng/routes/DependencyAnalyticsTest.java
src/test/java/com/redhat/ecosystemappeng/routes/integration/VulnerabilityProviderTest.java

Add license header

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/report/DependencyReportWrapper.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java
src/main/java/com/redhat/ecosystemappeng/crda/model/Issue.java
src/main/resources/application.properties
src/main/resources/freemarker/templates/report.ftl
src/main/resources/freemarker/templates/styles.ftl
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java

Added html template to display a report.

HTML Report

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/report/DependencyReportWrapper.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/trustedcontent/TrustedContentBodyMapper.java
src/main/resources/freemarker/templates/report.ftl
src/test/java/com/redhat/ecosystemappeng/crda/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/resources/__files/full_report.html

* The critical severity was not being rendered properly
* The recommendation link was not pointing to the right recommended package

fix recommendation link and critical severity

---

.gitignore

chore: update gitignore to ignore build target folder

---

src/main/resources/freemarker/templates/report.ftl

Added the new shield icon for RH recommendation.

New shield icon

---

pom.xml
src/main/java/com/redhat/ecosystemappeng/crda/config/CustomReflectionConfiguration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/Constants.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/VulnerabilityProvider.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/backend/BackendUtils.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/backend/CrdaBackendIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTransformer.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/tidelift/TideliftIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/trustedcontent/TrustedContentIntegration.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/ComponentAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/VulnerabilityProviderTest.java

Upgrade to Quarkus 3.0.2.Final

Quarkus3.0

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/GraphUtils.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/ComponentAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/resources/__files/empty_response.json
src/test/resources/__files/empty_snyk_report.json
src/test/resources/empty_dependencies.txt

Allow empty dependency graphs

---

src/main/resources/META-INF/openapi.yaml

chore: added highestVulnerability to openapi spec

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java
src/main/resources/application.properties
src/main/resources/freemarker/templates/report.ftl
src/main/resources/freemarker/templates/styles.ftl
src/test/resources/__files/full_report.html

Added modal to display vex and sbom links.

Added modal

---

src/main/java/com/redhat/ecosystemappeng/crda/model/DependencyReport.java
src/main/resources/freemarker/templates/report.ftl
src/test/resources/__files/full_report.html

Enhanced display of remediations to show the count  and whether they're direct or transitive.

TC-184: Enhanced display of remediations

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/GraphUtils.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/ProviderAggregationStrategy.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTransformer.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykAggregationStrategy.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/model/GraphRequest.java
src/main/java/com/redhat/ecosystemappeng/crda/model/ProviderStatus.java
src/main/resources/META-INF/openapi.yaml
src/test/java/com/redhat/ecosystemappeng/crda/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/resources/__files/component_snyk.json
src/test/resources/__files/empty_response.json
src/test/resources/__files/expected_dep_snyk.json

Adds status information about the interaction with the configured vulnerability providers;
```
"providerStatuses": [
{
"message": "OK",
"ok": true,
"provider": "snyk",
"status": 200
}
]
```
```
"providerStatuses": [
{
"message": "HTTP operation failed invoking https://app.snyk.io/api/v1 with statusCode: 401",
"ok": false,
"provider": "snyk",
"status": 401
}
]
```

Add status report for vulnerability providers

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java

Disable showing Snyk links for private issues

Always show issue data

---

src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTransformer.java
src/main/java/com/redhat/ecosystemappeng/crda/model/CvssScoreComparable.java
src/main/java/com/redhat/ecosystemappeng/crda/model/DependencyReport.java
src/main/java/com/redhat/ecosystemappeng/crda/model/TransitiveDependencyReport.java
src/test/resources/__files/component_snyk.json
src/test/resources/__files/expected_dep_snyk.json

Sort deps and transitive by highestVulnerability.cvssScore (#47)

---

src/main/resources/freemarker/templates/report.ftl
src/main/resources/freemarker/templates/styles.ftl
src/test/resources/__files/full_report_no_token.html
src/test/resources/__files/full_report_token.html

Changed report alignment.

---

src/main/resources/freemarker/templates/report.ftl
src/main/resources/freemarker/templates/styles.ftl
src/test/java/com/redhat/ecosystemappeng/crda/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/TokenValidationTest.java
src/test/resources/__files/report_error.html
src/test/resources/__files/report_no_token.html
src/test/resources/__files/report_token.html
src/test/resources/__files/report_unauthorized.html

Adds error and warning messages when the backend cannot retrieve a valid response from the vulnerability providers.
Adds a "no results" message when no data is retrieved

Show errors and empty table in HTML report

---

src/main/resources/freemarker/templates/report.ftl
src/main/resources/freemarker/templates/styles.ftl
src/test/resources/__files/report_error.html
src/test/resources/__files/report_no_token.html
src/test/resources/__files/report_token.html
src/test/resources/__files/report_unauthorized.html

Added an arrow up image for when the row is expanded.

TC-187: Added an arrow up image

---

.github/workflows/inform-cli.yml

Error caught in [this workflow run](https://github.com/RHEcosystemAppEng/crda-backend/actions/runs/5456067184/jobs/9928365350).

ci: fixed inform-cli error

---

.github/workflows/ci.yaml
src/main/java/com/redhat/ecosystemappeng/exhort/integration/backend/ExhortBackendIntegration.java
src/main/resources/freemarker/templates/report.ftl
src/test/resources/__files/reports/report_all_no_snyk_token.html
src/test/resources/__files/reports/report_all_token.html
src/test/resources/__files/reports/report_error.html
src/test/resources/__files/reports/report_forbidden.html
src/test/resources/__files/reports/report_unauthorized.html

refactor: rename to exhort missing resources

---

src/main/java/com/redhat/exhort/integration/report/ReportIntegration.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java

fix: support multipart/mixed for HTTP/2

---

src/main/java/com/redhat/ecosystemappeng/exhort/integration/backend/ExhortBackendIntegration.java
src/main/java/com/redhat/ecosystemappeng/exhort/integration/report/ReportIntegration.java
src/main/resources/freemarker/templates/report.ftl
src/test/java/com/redhat/ecosystemappeng/exhort/integration/DependencyAnalysisTest.java
src/test/resources/__files/reports/report_all_no_snyk_token.html
src/test/resources/__files/reports/report_all_token.html
src/test/resources/__files/reports/report_error.html
src/test/resources/__files/reports/report_forbidden.html
src/test/resources/__files/reports/report_unauthorized.html

[0.1.x] fix: support multipart/mixed for HTTP/2

---

.tekton/exhort-ci.yaml
src/main/docker/Dockerfile.jvm
src/main/docker/Dockerfile.multi-stage

Add tekton CI configuration pipeline

feat: [main] add tekton ci pipeline

---

.tekton/exhort-ci.yaml
src/main/docker/Dockerfile.jvm
src/main/docker/Dockerfile.multi-stage

Add tekton pipeline CI configuration and update the multi-stage to include the `api-spec` folder

feat: add tekton ci pipeline

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/backend/sbom/SbomParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxParser.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykRequestBuilder.java
src/main/java/com/redhat/exhort/model/DependencyTree.java
src/main/java/com/redhat/exhort/model/GraphRequest.java
src/test/java/com/redhat/exhort/integration/backend/ProviderAggregatorTest.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java
src/test/resources/__files/snyk/empty_request.json
src/test/resources/__files/snyk/maven_request.json
src/test/resources/cyclonedx/unsupported-invalid-sbom.json

fix: allow unknown dep tree

---

src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java

Fix [TC-524](https://issues.redhat.com/browse/TC-524)
Related to https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/45

fix: Resolve CycloneDX dependency common tree

---

src/main/java/com/redhat/exhort/integration/report/ReportTransformer.java
src/test/java/com/redhat/exhort/integration/report/ReportTransformerTest.java

Fix [TC-535](https://issues.redhat.com/browse/TC-535)

fix: sort direct vulnerabilities

---

dashboards/grafana-dashboard-exhort.configmap.yaml
src/main/java/com/redhat/exhort/config/metrics/CustomMetrics.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TrustedContentIntegration.java

chore: latency dashboard

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Add latency histogram for Snyk requests

chore: latency histograms for Snyk

---

.tekton/exhort-it-pull-request.yaml
.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml

Follow [migration guide](https://github.com/redhat-appstudio/build-definitions/blob/main/task/deprecated-image-check/0.3/MIGRATION.md)

chore: remove ws from deprecated-image-check:0.3 image

---

README.md
src/main/java/com/redhat/exhort/analytics/AnalyticsService.java
src/main/java/com/redhat/exhort/analytics/segment/Context.java
src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java

Allow clients to send more telemetry data

feat: Enhance telemetry data

---

src/main/java/com/redhat/exhort/api/PackageRef.java
src/main/java/com/redhat/exhort/integration/backend/BackendUtils.java
src/test/java/com/redhat/exhort/api/PackageRefTest.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java

Fix #161 
It also yields clearer error messages

fix: npm package ns parsing and enhance logs

---

ui/src/components/ChartCard.tsx
ui/src/components/SummaryCard.tsx

Changed Summary look based on the mockup design.

Changed Summary look.

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>

add Grafana SLO panel

---

src/test/java/com/redhat/exhort/integration/AnalysisTest.java
src/test/java/com/redhat/exhort/integration/HtmlReportTest.java

Created separate class for HTML Report testing.

Separated HTML Report Tests

---

src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/exhort/integration/AnalysisV3Test.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java
src/test/resources/__files/reports/report_all_no_snyk_token.json
src/test/resources/__files/reports/report_all_token.json
src/test/resources/__files/reports/v3/report_all_no_snyk_token.json
src/test/resources/__files/reports/v3/report_all_token.json

Transitive dependencies from multiple common parents were omitted.

fix: show issues from dependencies

---

catalog-info.yaml

Adding backstage configuration - catalog-info.yaml

Adding backstage configuration - catalog-info.yaml

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java

Fix [TC-706](https://issues.redhat.com/browse/TC-706)

fix: oss-index cannot aggregate big requests

---

src/main/resources/freemarker/templates/generated/main.css
ui/src/index.css

Jira: https://issues.redhat.com/browse/TC-416
TC-416: fixed the theme color for the report.

TC-416: Color Theme

---

src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykResponseHandler.java
src/main/java/com/redhat/exhort/model/ProviderResponse.java
src/test/java/com/redhat/exhort/integration/providers/ProviderResponseHandlerTest.java

Fix [TC-765](https://issues.redhat.com/browse/TC-765)

fix: issue with invalid oss-index credentials

---

deploy/exhort.yaml
deploy/openshift/template.yaml
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/resources/application.properties

feat: revert trustification-ossindex customization

---

deploy/openshift/template.yaml

To avoid OOM issue when running performance tests

increase pod memory limit

---

pom.xml
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexRequestBuilder.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TcResponseAggregation.java

Fix [TC-823](https://issues.redhat.com/browse/TC-823)

fix: don't recommend for same package version

---

src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/test/java/com/redhat/exhort/integration/providers/ProviderResponseHandlerTest.java

Fix [TC-833](https://issues.redhat.com/browse/TC-833)

fix: properly calculate the direct highestVulnerability

---

src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/test/java/com/redhat/exhort/integration/providers/ProviderResponseHandlerTest.java

Fix [TC-847](https://issues.redhat.com/browse/TC-847)

fix: add recommendations when no issues are reported

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Adapt cluster names in grafana dashboard.

[exhort migration] add new clusters to dashboard

---

src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxProcessingException.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxWrapper.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SpdxWrapperTest.java
src/test/resources/spdx/versions/SPDX-2.2.json
src/test/resources/spdx/versions/SPDX-2.3.json

Implements [TC-873](https://issues.redhat.com/browse/TC-873)

feat: support spdx 2.2

---

pom.xml
src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/resources/application.properties
src/test/java/com/redhat/exhort/integration/AnalysisTest.java

Implements [TC-903](https://issues.redhat.com/browse/TC-903)

feat: allow gzip content-encoding

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>

chore: add links to Grafana Explore logs

---

src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java

Fix [APPENG-2271](https://issues.redhat.com/browse/APPENG-2271)

feat: consider components with unknown deps as direct deps

---

src/main/java/com/redhat/exhort/analytics/segment/AuthenticationHeaderFactory.java
src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykRequestBuilder.java
src/main/resources/application.properties
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java

Fix [APPENG-2289](https://issues.redhat.com/browse/APPENG-2289)

feat: add user-agent snyk HTTP Header

---

src/main/java/com/redhat/exhort/analytics/AnalyticsService.java

Fix [APPENG-2313](https://issues.redhat.com/browse/APPENG-2313)

feat: add pkgType count to telemetry event

---

src/main/java/com/redhat/exhort/analytics/AnalyticsService.java
src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/osvnvd/OsvNvdIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykIntegration.java

Fix [APPENG-2314](https://issues.redhat.com/browse/APPENG-2314)

feat: add telemetry property for requests using credentials

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java
src/test/java/com/redhat/exhort/integration/backend/BackendUtilsTest.java
src/test/resources/cyclonedx/empty-sbom.json
src/test/resources/cyclonedx/invalid-sbom.json
src/test/resources/cyclonedx/mixed-sbom.json
src/test/resources/cyclonedx/unsupported-invalid-sbom.json
src/test/resources/spdx/invalid-sbom.json

Fix [APPENG-2320](https://issues.redhat.com/browse/APPENG-2320)

fix: CycloneDX strict validation

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java

fix: make error processing asynchronous

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java

Fix [APPENG-2333](https://issues.redhat.com/browse/APPENG-2333)

fix: prevent race condition when processing the monitoring context

---

pom.xml

Avoid dependency with org.json:json:20230227 which has a vulnerability (GHSA-4jq9-2xhw-jpx7)

chore(deps): upgrade spdx to avoid dep with vulnerable org.json:json

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java

Fix [APPENG-2336](https://issues.redhat.com/browse/APPENG-2336)

fix: missing track event

---

ui/src/utils/utils.ts

fix: typo in utils.ts

---

deploy/exhort.yaml
deploy/openshift/template.yaml

Fix: [APPENG-2345](https://issues.redhat.com/browse/APPENG-2345)

chore(deps): disable Snyk integration

---

ui/src/mocks/reportDocker.mock.ts
ui/src/utils/utils.ts

fix: Implement URL decoding for original purl.

fix: decoding original purl if needed

---

README.md

Update README.md for batch-analysis

docs: update for batch-analysis

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Added panels for visualizing JVM threads

chore: add JVM threads panels

---

pom.xml
src/main/java/com/redhat/exhort/integration/providers/osvnvd/OsvNvdResponseHandler.java
src/test/resources/__files/osvnvd/maven_report.json

Fix[APPENG-2424](https://issues.redhat.com/browse/APPENG-2424)
Depends on https://github.com/RHEcosystemAppEng/ONguard/pull/67

feat!: adapt to osv metrics

---

.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml
deploy/exhort.yaml
deploy/openshift/template.yaml
pom.xml
src/main/docker/Dockerfile.jvm.staged
src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/cache/CacheService.java
src/main/java/com/redhat/exhort/integration/cache/RedisCacheService.java
src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TcResponseAggregation.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TrustedContentIntegration.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TrustedContentRequestBuilder.java
src/main/java/com/redhat/exhort/model/trustedcontent/CachedRecommendation.java
src/main/java/com/redhat/exhort/model/trustedcontent/TrustedContentCachedRequest.java
src/main/resources/application.properties
src/test/java/com/redhat/exhort/integration/cache/RedisCacheServiceTest.java
src/test/java/com/redhat/exhort/integration/trustedcontent/TrustedContentRequestBuilderTest.java
src/test/resources/__files/reports/batch_report_all_token.json

Fix [APPENG-2332](https://issues.redhat.com/browse/APPENG-2332)

feat: cache recommendations

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Fix [APPENG-2431](https://issues.redhat.com/browse/APPENG-2431)

chore(deps): add elasticache metrics to grafana dashboard

---

src/main/java/com/redhat/exhort/integration/report/ReportTemplate.java

Jira: [TC-1530](https://issues.redhat.com/browse/TC-1530)
Removed ASCII code for the dependency name.

fix: report was loading with ASCII code for the dependency name

---

.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml

chore(deps): upgrade to buildah-8gb:0.2

---

.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml
.tekton/settings.xml
README.md
catalog-info.yaml
devfile.yaml
pom.xml

chore: update references to trustification org

---

pom.xml
src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/test/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParserTest.java
src/test/resources/application.properties
src/test/resources/cyclonedx/empty-sbom.json
src/test/resources/cyclonedx/unknown-deps.json
src/test/resources/cyclonedx/valid-1.6.json

Fix https://github.com/trustification/exhort/issues/423

feat: support cyclonedx 1.6

---

src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/backend/sbom/SbomParserFactory.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexRequestBuilder.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/tpa/TpaIntegration.java
src/main/java/com/redhat/exhort/integration/providers/tpa/TpaRequestBuilder.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TcResponseAggregation.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TcResponseHandler.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TrustedContentIntegration.java
src/main/java/com/redhat/exhort/integration/trustedcontent/TrustedContentRequestBuilder.java
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java
src/test/java/com/redhat/exhort/integration/HtmlReportTest.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java
src/test/java/com/redhat/exhort/integration/trustedcontent/TcResponseHandlerTest.java

feat: split tpa requests

---

src/test/java/com/redhat/exhort/integration/modelcards/ModelCardIntegrationTest.java

Add missing it tests for the ModelCard Integration
Follow up on #435

feat: add it for model card integration

---

pom.xml
src/main/java/com/redhat/exhort/model/modelcards/Guardrail.java
src/main/java/com/redhat/exhort/model/modelcards/GuardrailScope.java
src/main/java/com/redhat/exhort/modelcards/GuardrailRepository.java
src/main/java/com/redhat/exhort/modelcards/ModelCardService.java
src/main/resources/db/README.md
src/main/resources/db/migration/V4__create_guardrail_tables.sql
src/main/resources/db/migration/V5__insert_guardrail_data.sql
src/test/java/com/redhat/exhort/modelcards/ModelCardServiceTest.java
src/test/resources/db/h2/V2__insert_data.sql

feat: add guardrails to model card report

---

dashboards/grafana-dashboard-exhort.configmap.yaml

Default to production instance

fix: exhort rds grafana regex

---

.tekton/settings.xml
README.md
pom.xml

chore: update exhort-api-spec references

---

src/main/java/com/redhat/exhort/integration/report/ReportIntegration.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java

fix: incorrect multipart/mixed response

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/monitoring/MonitoringProcessor.java
src/test/java/com/redhat/exhort/extensions/OidcWiremockExtension.java
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java

Fix https://github.com/trustification/exhort/issues/482
Fix IT expectations for OIDC scenarios

fix: update test expectations and stubs
