trustification/exhort

pom.xml

When working with maven 3.9.x we get the following warning for the `surefire` and `failsafe` plugins:
```shell
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
```
This is fixed with the latest version of the [surefire](https://maven.apache.org/surefire/maven-surefire-plugin/jira-report.html) and [failsafe](https://maven.apache.org/surefire/maven-failsafe-plugin/jira-report.html), version 3.0.0, which includes [this fix](https://issues.apache.org/jira/browse/SUREFIRE-2154).
This was tested with both my local 3.9.1 version and the project's wrapper 3.8.4 version.

build(deps): bump surefile and failsafe plugins to latest 3.0.0

---

README.md
src/main/java/com/redhat/ecosystemappeng/crda/integration/Constants.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/VulnerabilityProvider.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/backend/CrdaBackendIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTemplate.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/report/ReportTransformer.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykAggregationStrategy.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/model/Issue.java
src/main/resources/META-INF/openapi.yaml
src/main/resources/application.properties
src/main/resources/freemarker/templates/report.ftl
src/test/java/com/redhat/ecosystemappeng/crda/integration/DependencyAnalysisTest.java
src/test/resources/__files/component_snyk.json
src/test/resources/__files/expected_dep_snyk.json
src/test/resources/__files/expected_report.json
src/test/resources/__files/full_report_no_token.html
src/test/resources/__files/full_report_token.html
src/test/resources/__files/snyk_report.json
src/test/resources/__files/trustedContent_vex_report.json

Verbose mode helps retrieving only the summary for the JSON report.
When clients do not provide a token for the vulnerability provider data will be limited in both the JSON and HTML reports.

Add verbose and limit data for anonymous requests

---

.github/workflows/ci.yaml
README.md
pom.xml
src/main/java/com/redhat/ecosystemappeng/crda/integration/Constants.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/backend/CrdaBackendIntegration.java
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykIntegration.java
src/main/resources/META-INF/openapi.yaml
src/test/java/com/redhat/ecosystemappeng/crda/integration/TokenValidationIT.java
src/test/java/com/redhat/ecosystemappeng/crda/integration/TokenValidationTest.java

Add token validation endpoint to allow clients validate the token without having to send a vulnerability request.
This is useful when configuring the CLI or IDE.

Add token validation endpoint

---

.github/workflows/inform-cli.yml

ci: prevent the inform cli workflow from running and failing in forks

---

README.md
src/main/java/com/redhat/ecosystemappeng/crda/integration/snyk/SnykIntegration.java
src/main/resources/META-INF/openapi.yaml
src/test/resources/__files/report_error.html
src/test/resources/__files/report_unauthorized.html

Provide a more detailed message in the providerStatuses response and in the HTML report.
Fix #68 
```json
"providerStatuses": [
{
"message": "Unauthorized: Verify the credentials provided are valid.",
"ok": false,
"provider": "snyk",
"status": 401
}
]
```
```json
"providerStatuses": [
{
"message": "Unauthorized: The provided credentials don't have the required permissions.",
"ok": false,
"provider": "snyk",
"status": 403
}
]
```
```json
"providerStatuses": [
{
"message": "Too many requests: The rate limit has been exceeded.",
"ok": false,
"provider": "snyk",
"status": 429
}
]
```

feat: Refine error codes

---

.github/workflows/inform-cli.yml

The [crda-cli](https://github.com/RHEcosystemAppEng/crda-cli) project is being dropped.
The _inform-cli_ workflow should inform the api libs projects, [crda-javascript-api](https://github.com/RHEcosystemAppEng/crda-javascript-api) and [crda-java-api](https://github.com/RHEcosystemAppEng/crda-java-api), instead.

ci: update inform-cli workflow to inform the api libs instead of the cli

---

src/main/resources/META-INF/openapi.yaml
src/main/resources/freemarker/templates/report.ftl
src/test/resources/__files/reports/report_all_no_snyk_token.html
src/test/resources/__files/reports/report_all_token.html

The [exhort-java-api](https://github.com/RHEcosystemAppEng/exhort-java-api) Integration Tests were failing because of a missing field in the OpenAPI

fix: remove extra line in report and add purl to openapi

---

src/main/resources/freemarker/templates/report.ftl
src/test/resources/__files/reports/report_all_no_snyk_token.html
src/test/resources/__files/reports/report_all_token.html
src/test/resources/__files/reports/report_error.html
src/test/resources/__files/reports/report_forbidden.html
src/test/resources/__files/reports/report_unauthorized.html

Imported a new URL for patternFly CDN to fix the table. Replaced images with SVG for the icons to be displayed in the summary card.

Css report fix

---

.github/workflows/cicd.yaml

The workflow includes 2 jobs.
1. build image with Buildah according to Dockerfile.native-micro, push image to quay.io/ecosystem-appeng/exhort:latest
2. log in to Openshift SSSC cluster and patch image with new image digest in exhort-dev deployment resource

GitHub Actions CICD Workflow

---

.github/workflows/ci.yaml
.github/workflows/cicd.yaml

1. Added validation of workflow requirements job that checks if all required secret have been configure, prints feedback to log. 
2. Added deployment monitoring step to deploy to Openshift job that monitors the progress of the deployment update. It continuously checks the status of the deployment and waits for all the new pods to become ready and available to handle traffic. 
3. Changed `mvn package -Pnative` to run `mvn verify -Pnative` instead in order to include integration tests in the workflow as well as build. 
4. Removed trigger `on push` from CI workflow as integration tests will be done in CICD workflow.

chore: add pre and post action validations

---

deploy/openshift/template.yaml

added a service account at the request of the SRE team

chore: add serviceAccount for deployment

---

src/main/java/com/redhat/exhort/integration/report/ReportTransformer.java
src/test/java/com/redhat/exhort/integration/report/ReportTransformerTest.java

Fix [TC-526](https://issues.redhat.com/browse/TC-526)
Affects/Depends on https://github.com/RHEcosystemAppEng/exhort-javascript-api/issues/44

fix: summary count unique transitive dependencies

---

src/main/java/com/redhat/exhort/integration/backend/BackendUtils.java
src/main/java/com/redhat/exhort/integration/report/ReportTransformer.java

Fix [TC-526](https://issues.redhat.com/browse/TC-526)

fix: missing direct dependency

---

src/main/java/com/redhat/exhort/api/PackageRef.java
src/test/java/com/redhat/exhort/api/PackageRefTest.java

**Description:**
In case there is a Golang module/package with no group/namespace ( e.g. "pkg:golang/go.opencensus.io@v0.21.0"), need to parse the name only and ignoring the  namespace part which is null
Fixes: #152

fix: sbom golang purl parsing failing 

---

src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxParser.java
src/main/java/com/redhat/exhort/model/DependencyTree.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java
src/test/java/com/redhat/exhort/integration/report/ReportTransformerTest.java
src/test/resources/cyclonedx/cyclic-sbom.json
src/test/resources/spdx/cyclic-sbom.json

fix #153 
For CycloneDX it's just a matter of stopping the recursive function when the cyclic dependency is detected.
However for SPDX, the root node does not point to the direct dependencies so it is not possible to draw a reliable graph in that case as there are multiple alternatives. In that case it will be better to throw a validation error.

fix: support cyclic dependencies

---

.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml

Skip trigger pipelines for configuration only changes (in particular `dashboard` folder)
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>

chore: exclude configuration folders from pipeline

---

src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/backend/sbom/SbomParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxWrapper.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java
src/test/resources/spdx/reverse-sbom.json

fix: spdx relationships

---

src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/integration/backend/sbom/SbomParser.java
src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykIntegration.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykRequestBuilder.java
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java
src/test/resources/spdx/unsupported-mixed-sbom.json

feat: delegate client errors to each provider

---

README.md

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>

docs: correct spelling of README

---

src/main/java/com/redhat/exhort/integration/Constants.java
src/main/java/com/redhat/exhort/integration/backend/BackendUtils.java
src/main/java/com/redhat/exhort/integration/backend/ExhortIntegration.java
src/main/java/com/redhat/exhort/monitoring/MonitoringProcessor.java
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java
src/test/java/com/redhat/exhort/integration/AnalysisTest.java
src/test/java/com/redhat/exhort/integration/HtmlReportTest.java
src/test/java/com/redhat/exhort/integration/TokenValidationTest.java
src/test/java/com/redhat/exhort/integration/backend/BackendUtilsTest.java

1. Generate ex-request-id , a sha256 digest of the timestamp + rhda_token if exists ( otherwise random real number in the range of [0,1] ). 
2.  add this generated value as an exchange property ( Camel exchange property) called exRequestId.
3. propagate it to all original request message paths , all error messages and on all error paths as a metadata field with the name of the property.
4. add to the response of all paths and cases( 200, 422 , 5xx , etc.)  the value  of generted ex-request-id as a response header.
Handle: https://issues.redhat.com/browse/APPENG-2183.
_**Why not using UUID generator and that's it?**_
Because RHDA Token is already one of the metadata fields in logs messages sent to sentry, and usually clients send RHDA  Token as Pseudo random generated uuid, and we want a …

feat: Generate and add ex-request-id response header

---

deploy/openshift/template.yaml

chore: delete backstage resources

---

src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxParser.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykRequestBuilder.java
src/test/java/com/redhat/exhort/integration/backend/sbom/SbomParserTest.java

Fix [APPENG-2282](https://issues.redhat.com/browse/APPENG-2282)

fix: correct contained_by/contains relationships and filter duplicates in Snyk

---

src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java

fix: allow CycloneDX SBOMs without metadata

---

src/main/java/com/redhat/exhort/integration/providers/osvnvd/OsvNvdResponseHandler.java
src/main/java/com/redhat/exhort/model/CvssParser.java
src/test/java/com/redhat/exhort/integration/providers/osvnvd/OsvNvdResponseHandlerTest.java
src/test/java/com/redhat/exhort/model/CvssParserTest.java
src/test/resources/__files/osvnvd/maven_report.json
src/test/resources/__files/reports/report_all_token.json
src/test/resources/__files/reports/v3/report_all_token.json

Fix [TC-988](https://issues.redhat.com/browse/TC-988)

fix: support cvssV2 conversion to V3

---

src/main/java/com/redhat/exhort/integration/trustedcontent/TcResponseHandler.java
src/test/resources/__files/trustedcontent/simple.json

Fix [APPENG-2319](https://issues.redhat.com/browse/APPENG-2319)

fix: avoid duplicated CVE recommendations

---

.github/workflows/ci.yaml
.github/workflows/cicd.yaml
.tekton/exhort-pull-request.yaml
.tekton/exhort-push.yaml
deploy/exhort.yaml
deploy/openshift/template.yaml
pom.xml
src/main/docker/Dockerfile.jvm
src/main/docker/Dockerfile.jvm.staged
src/main/docker/Dockerfile.multi-stage
src/main/java/com/redhat/exhort/analytics/AnalyticsService.java
src/main/java/com/redhat/exhort/integration/backend/sbom/cyclonedx/CycloneDxParser.java
src/main/java/com/redhat/exhort/integration/backend/sbom/spdx/SpdxParser.java
src/main/java/com/redhat/exhort/integration/providers/ProviderResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/ossindex/OssIndexResponseHandler.java
src/main/java/com/redhat/exhort/integration/providers/snyk/SnykRequestBuilder.java
src/main/resources/application.properties
src/test/java/com/redhat/exhort/integration/AbstractAnalysisTest.java

There is no need to maintain the native build. Moving to simpler JVM builds.
* Moved to jboss.Logging because there were duplicated LoggingManagers in the classpath
* Upgraded builds to Java 21 and node 20
* Fixed wrong import for the `Files` helper in test classes

chore(deps): move to jvm build

---

src/main/java/com/redhat/exhort/monitoring/SentryMonitoringClientFactory.java
src/main/java/com/redhat/exhort/monitoring/impl/SentryMonitoringClient.java

Fix [APPENG-2391](https://issues.redhat.com/browse/APPENG-2391)
Introduced by https://github.com/RHEcosystemAppEng/exhort/pull/314

fix: reuse Hub instances for Sentry events

---

pom.xml

fix: validate 1.5 and 1.6 spdx licenses using cyclonedx 11.0.0
